name: setup-lua
description: action to setup Lua and LuaRocks

branding:
  icon: 'moon'
  color: 'blue'

inputs:
  lua-version:
    description: version of Lua to setup
    required: false
    default: '5.3.5'
  luarocks-version:
    description: version of LuaRocks to setup
    required: false
    default: '3.1.3'

runs:
  using: 'node16'
  main: 'dist/index.js'
